Fix image rendering in Electron forge branch.
Zettlr/Zettlr pull request #1247
Opened 2020-09-07 12:54 UTC by Kangie

#  Description
Fix image rendering in electron forge branch.

# Changes
Modified `makeAbsoluteCachefreeURL` to use `safe-file://`
Removed cache-buster from same function.

## Additional information
Fixes #1228

Tested on: 
Gentoo Linux.

2020-09-09 14:37 UTC, nathanlesage requested changes
Thanks for implementing! Just one question: can you include an image, then modify it externally and remove the image preview and have Zettlr re—render it with the changes visible? (This was the reason we had the "cache-breaker" for)

Plus please adapt the corresponding unit-test for the function, which will now break.

2020-09-09 22:37 UTC, Kangie commented
Hi Nathan,

The `safe-file://` handler says that it prevents caching of local files, and testing on Linux and Windows indicates that this works for both absolute and relative paths with these changes.

I'll have a look at the unit tests and update my PR!

2020-09-10 12:08 UTC, Kangie commented
@nathanlesange

There's actually no unit test for this function. There's one for the function that runs to make paths absolute before export, and one to make valid URIs, but not one for this. I suspect that's because, until recently, this function was part of zettlr-plugin-render-images. (Also, we should standardise terminololgy - URL or URI?)

So, nothing fails. This function returns `safe-file:` because we're not allowed to use `file://` from the renderer.
We should probably develop a test at some point, but I'm honestly pretty fried right now.

Will you accept this PR as-is with the promise of a unit test when I have more free time?

2020-09-10 13:50 UTC, nathanlesage commented
Ahhhh right, I've lost the overview during the forge migration - then let's keep it in mind - in general I'd like to have unit tests for everything in the util directory, but that's work in progress, so all good if the other changes are in :)

2020-09-10 14:25 UTC, Kangie commented
Yeah, go ahead. This will fix the linting errors in all other PRs as a happy side-effect.

I'm comfortable with the way that images are being handled, and spent all day today working with content using this code.

2020-09-11 11:18 UTC, nathanlesage approved these changes

2020-09-11 11:19 UTC, merged