Feature/2344/folder first
Zettlr/Zettlr pull request #2862
Opened 2021-11-26 23:26 UTC by newhinton

## Description
fixes #2344

## Changes
added a checkbox and the corresponding config to sort folders above files.

Tested on: Kubuntu 20.04

2021-11-26 23:43 UTC, newhinton commented
It does not resort the list on a change in the settings. A manual refresh, a restart or a change in the sorting-order is required to apply the change at the moment

2021-11-26 23:54 UTC, newhinton commented
Also, maybe it does make sense to add a css-class to each last element of a type. So that we can add a small margin-bottom to create a little space between folders/files to make differentiation easier

2021-11-30 17:51 UTC, nathanlesage commented
> Also, maybe it does make sense to add a css-class to each last element of a type. 

Sounds like a good idea, but maybe then also on the first element. I'd suggest we address this in a separate PR after the Vue 3 migration which is almost finished. If you'd like to, please feel free to review the corresponding PR that'll be incoming probably on the weekend, to speed that process up. This is also what kind of prevents me from testing and merging your PRs right now … I'll see to getting to that in the coming days.

2021-12-04 14:49 UTC, nathanlesage requested changes
Looks pretty good. I got only two small comments, but then it's almost ready for merging.

One thing we might need to think about is that just changing this doesn't immediately apply. We need to find a way to re-sort all directories afterwards. So what we might need to do is add a listener for this config change in the FSAL that triggers a recursive re-sort so that the changes are applied immediately. Do you feel up to that task as well?

2021-12-04 14:49 UTC, nathanlesage commented on source/main/modules/fsal/util/sort.ts
> +  }
I would make this an else here so it's clear that one of these results will happen; I think it makes it cleaner!

2021-12-04 14:49 UTC, nathanlesage commented on source/win-preferences/schema/general.js
> +          label: trans('dialog.preferences.sortFoldersFirst'),
To make the translation string consistent with the other translations, please convert this to snake_case.

2021-12-04 15:08 UTC, newhinton commented
> So what we might need to do is add a listener for this config change in the FSAL that triggers a recursive re-sort so that the changes are applied immediately. Do you feel up to that task as well?

Wouldn't resorting also solve #2864 ? Albeit we probably have too keep track of expanded folders... i'll think about it

2021-12-04 15:25 UTC, nathanlesage commented
> Albeit we probably have too keep track of expanded folders... i'll think about it

That is another thing that would be really cool to have. Currently, Zettlr does not at all keep track of opened folders. But, rather a feat than a fix!

Shall we just merge this thing and then figure out a way to hot reload the directory tree in a separate PR?

If so, it would be great if you had a suggested wording for the English+German translations of the new translation strings we have in this PR, so I can add them to Translate!

2021-12-04 15:25 UTC, nathanlesage approved these changes

2021-12-04 16:00 UTC, newhinton commented
> If so, it would be great if you had a suggested wording for the English+German translations of the new translation strings we have in this PR, so I can add them to Translate!

dialog.preferences.sortFoldersFirst.en: `Show folders above notes`
dialog.preferences.sortFoldersFirst.de: `Zeige Ordner vor Notizen`

albeit i am not sure about "notes" is the right term, but "files" may be too generic or simply not friendly enough

2021-12-04 17:20 UTC, nathanlesage commented
> but "files" may be too generic or simply not friendly enough

I know what you mean, but since the wording is generally "files" and not "notes", this might be better. I will add that to the Translation service; thank you!

And also, welcome to the party with the first PR! ;D Now we just need this idea of reloading the file tree …

2021-12-04 17:23 UTC, merged